### ISSUE TITLE
Interaction Breaks

### ISSUE THREAD

**Issue by Redstoneguy129** [Apacheli/Space#3]
Interaction doesn't have data.

`
error: Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    if (interaction.data.name === "ping") {
`

Code:
`
for await (const [interaction, respond] of server) {
    console.log(interaction)
    if (interaction.data.name === "ping") {
        respond({
            type: InteractionResponseType.ChannelMessageWithSource,
            data: { content: "pong" },
        });
    }
}
`

interaction seems to just be a string containing the value: "COMMAND"

**Comment by Apacheli** [comment]
Oh, the example on the README is incorrect, I'll need to fix that. The correct way is to do:
```ts
for (const [interaction, respond] of server.listen("COMMAND")) {
```
or:
```ts
for await (const [event, interaction, respond] of server) {
  if (event === "COMMAND") {
```
